name: Build
description: Build application with Maven and create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "Dockerfile"
runs:
  using: composite
  steps:
    - name: Create docker image
      shell: bash
      run: docker build . --file ./src/main/docker/Dockerfile.jvm --tag academy:$(date +%s)
    - name: Check docker image
      shell: bash
      run: docker image ls
