name: Build
description: Build application with Maven and create a new Docker image
inputs:
  dockerfile_path:
    description: "Path to the Dockerfile"
    required: false
    default: "./src/main/docker/Dockerfile.jvm"
  image_name:
    description: "Image name"
    required: false
    default: "academy"
  tag_name:
    description: "Tag name"
    required: true
    default: ""
runs:
  using: composite
  steps:
    - name: "Set props in GITHUB_ENV"
      run: |
            if [ -z "${{inputs.tag_name}}" ]; then
              echo "TAG=$(date +%s)" >> $GITHUB_ENV
            else
            echo "TAG=${{inputs.tag_name}}" >> $GITHUB_ENV
            fi
            echo "DOCKER_IMAGE_NAME=${{inputs.image_name}}" >> $GITHUB_ENV
      shell: bash
    - name: Create docker image
      run: docker build . --file ${{inputs.dockerfile_path}} --tag ${{inputs.tag_name}}
      shell: bash
    - name: Check docker image
      shell: bash
      run: docker image ls
    - name: Push image to Docker Hub
      shell: bash
      run: |
            docker image tag $DOCKER_IMAGE_NAME:$TAG goncalofigueiredo462/academy:$TAG
            docker push goncalofigueiredo462/academy:$TAG


