CREATE SEQUENCE IF NOT EXISTS SEQ_RACK_ASSET_ID;
CREATE SEQUENCE IF NOT EXISTS SEQ_RACK_ID;
CREATE SEQUENCE IF NOT EXISTS SEQ_TEAM_ID;
CREATE SEQUENCE IF NOT EXISTS SEQ_BOOKING_ID;
CREATE SEQUENCE IF NOT EXISTS SEQ_TEAM_MEMBER_ID;



